openapi: 3.0.0
info:
  version: 0.2.0
  title: Auth
  description: Service for authentication and authorization.
  contact:
    name: n.batrakov
    email: n.batrakov@itexpert.ru
servers:
  - url: /api/auth

paths:
  /signin/basic:
    post:
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                type: object
                additionalProperties:
                  type: object
      security:
        - basic: []
  /signout:
    post:
      responses:
        '204':
          description: Success
  /validate:
    post:
      responses:
        '204':
          description: Success
      security:
        - bearer: []

components:
  securitySchemes:
    basic:
      type: http
      scheme: basic
    bearer:
      name: Authoriazation
      in: header
      type: apiKey