stages:
  - build
  - deploy

build_linux:
  stage: build
  only: [CI]
  tags: [docker-executor]
  image: microsoft/dotnet:sdk
  script: 
    - export VERSION=$(cat .version)
    - dotnet publish -c Release /property:Version=$VERSION -r linux-x64 -o /out/linux-x64
  artifacts:
    paths: [/out/linux-x64]
    untracked: true

deploy_nuget:
  stage: deploy
  only: [CI]
  tags: [docker-executor]
  image: microsoft/dotnet:sdk
  script:
    - export VERSION=$(cat .version)
    - dotnet pack -o nuget -c Release /property:Version=$VERSION
    - dotnet nuget push nuget/*.nupkg -s http://nuget.itexpert.ru/nuget/ -k password