openapi: 3.0.0
info:
  version: 0.0.1
  title: BusinessLogic
paths:
  /getServiceCatalogRoot:
    post:
      summary: Возвращает корневые элементы дерева каталога услуг, а также наиболее популярные шаблоны услуг для каждого "корня"
      tags:
        - ServiceCatalog

      parameters:
        - in: query
          name: numberOfServices
          description: Максимальное количество популярных услуг, которое требуется вернуть для "корня"
          schema:
            default: 3
            type: integer

      responses:
        '200':
          description: Корень дерева каталога услуг
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/getServiceCatalogRootResponse'

components:
  schemas:
    getServiceCatalogRootResponse:
      type: object
      properties:
        entities:
          description: Список услуг
          type: array
          items:
            description: Корневая услуга
            type: object
            required: [id, name]
            properties:
              id:
                description: Идентификатор услуга (ссылка на `Справочник.ITEXP_ШаблоныЗаполненияЗНО`)
                type: string
                format: guid
              name:
                description: Локализованное экранное имя услуги
                type: string
              description:
                description: Локализованное экранное описание услуги
                type: string
              icon:
                description: Иконка услуги
                type: string
                format: base64
              services:
                description: Популярные дочерние услуги
                type: array
                items:
                  type: object
                  required: [id, name]
                  properties:
                    id:
                      description: Идентификатор услуга (ссылка на `Справочник.ITEXP_ШаблоныЗаполненияЗНО`)
                      type: string
                      format: guid
                    name:
                      description: Локализованное экранное имя услуги
                      type: string
                    description:
                      description: Локализованное экранное описание услуги
                      type: string