openapi: 3.0.0
info:
  version: 0.0.1
  title: BusinessLogic
paths:
  /getServiceQuestionnaire:
    post:
      summary: Метод получения опросника каталога услуг
      description: |- 
        [Details](https://git.itexpert.ru/ITExpert/ITExpert.RITM/wikis/1c/api/service-catalog/get-questionnaire)
      tags:
        - ServiceCatalog
      
      parameters:
        - in: query
          name: template
          description: Идентификатор услуги
          required: true
          schema:
            type: string
            format: guid
          example: 5c7bfa7b-58e6-11e8-ae55-000c29626b10

      responses:
        '200':
          description: Опросник
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/getServiceQuestionnaireResponse'

components:
  schemas:
    typeMetadata:
      oneOf:
        - $ref: '#/components/schemas/scalarType'
        - $ref: '#/components/schemas/referenceType'
        - $ref: '#/components/schemas/unionType'
        - $ref: '#/components/schemas/enumerationType'
        - $ref: '#/components/schemas/collectionType'
    scalarType:
      description: примитивные значимые типы вроде строки, числа и т.п.
      type: object
      required: [type]
      properties:
        type:
          type: string
          enum:
            - Integer
            - Float
            - String
            - Boolean
            - DateTime
    referenceType:
      description: ссылочные типы, т.е. типы ссылающиеся на какую-то сущность в системе
      type: object
      required: [type, args]
      properties:
        type:
          type: string
          enum: [Reference]
        args:
          type: object
          required: [reference]
          properties:
            reference:
              description: Сущность, на которую ссылается значение типа
              type: string
    unionType:
      description: типы, значения которых могут принадлежать одному из фиксированного набора типов
      type: object
      required: [type, args]
      properties:
        type:
          type: string
          enum: [Union]
        args:
          type: object
          required: [types]
          properties:
            types:
              description: набор всевозможных типов, один из которых должно принять значение
              type: array
              minItems: 1
              items:
                $ref: '#/components/schemas/typeMetadata'
    enumerationType:
      description: типы с фиксированным набором значений
      type: object
      required: [type, args]
      properties:
        type:
          type: string
          enum: [Enumeration]
        args:
          type: object
          required: [values]
          properties:
            values:
              description: набор всевозможных значений типа
              type: array
              minItems: 1
              items:
                type: object
                required: [id]
                properties:
                  id:
                    description: идентификатор значения
                    type: string
                  title:
                    description: экранное имя значения
                    type: string
    collectionType:
      description: тип, описывающий набор значений с одинаковым типом
      type: object
      required: [type, args]
      properties:
        type:
          type: string
          enum: [Collection]
        args:
          type: object
          required: [itemsType]
          properties:
            itemsType:
              $ref: '#/components/schemas/typeMetadata'
    

    filter:
      description: Абстрактное дерево описывающее фильтрацию
      oneOf:
        - $ref: '#/components/schemas/filterLogicalNode'
        - $ref: '#/components/schemas/filterComparisonNode'
    filterLogicalNode:
      description: Узел, объединяющий между собой другие узлы фильтра через конъюнкцию или дезъюнкцию
      type: object
      required: [operator, nodes]
      properties:
        isNegative:
          description: если `True`, то логическое условие блока следует инвертировать
          type: boolean
          default: false
        operator:
          description: имя логического оператора сравнения
          type: string
          enum: [and, or]
        nodes:
          description: потомки узла дерева; массив узлов объединяемых одним логическим оператором
          type: array
          minItems: 1
          items:
            $ref: '#/components/schemas/filter'
    filterComparisonNode:
      description: Узел описывающий сравнение значения из источника с помощью указанного оператора
      type: object
      required: [operator]
      properties:
        field:
          description: поле фильтрумой сущности; источник значения
          type: string
        operator:
          description: оператор сравнения
          type: string
          enum:
            - equal
            - notEqual
            - greaterThan
            - greaterOrEqual
            - lesserThan
            - lesserOrEqual
            - Like
            - In
        value: {}
        isNegative:
          description: если `True`, то результат сравнения следует инвертировать
          type: boolean
          default: false


    questionnaireTrigger:
      description: условие на значение вопроса, которое, если срабатывает, вызывает какие-то действия над другими вопросами
      type: object
      properties:
        filter:
          $ref: '#/components/schemas/filter'
        actions:
          description: Действия, выполняемые при срабатывании триггера
          type: array
          items:
            $ref: '#/components/schemas/questionnaireAction'

    questionnaireAction:
      description: Действие над полем опросника
      type: object
      required: [type, question]
      properties:
        type:
          description: Идентификатор действия
          type: string
        question:
          description: Идентификатор вопроса
          type: string
        args:
          description: Аргрументы действия
          type: object
          additionalProperties: {}
        

    getServiceQuestionnaireResponse:
      type: object
      required: [groups, fields]
      properties:
        groups:
          description: Группирока вопросов
          type: array
          items:
            type: object
            required: [name, fields]
            properties:
              name:
                type: string
              fields:
                type: array
                items:
                  type: string
        fields:
          description: Описание вопросов
          type: array
          items:
            description: Вопрос (одно поле формы)
            type: object
            required:
              - id
              - name
              - meta
              - value
              - visible
              - available
              - required
              - triggers
            properties:
              id:
                description: Идентификатор вопроса
                type: string
              name:
                description: Локализованное экранное имя вопроса
                type: string
              meta:
                $ref: '#/components/schemas/typeMetadata'
              value:
                description: Значение по-умолчанию вопроса
                oneOf:
                  - type: string
                  - type: number
                  - type: boolean
              visible:
                description: Видимость вопроса
                type: boolean
                default: false
              available:
                description: Доступность для заполнения вопроса
                type: boolean
                default: false
              required:
                description: Обязательность ответа на вопрос
                type: boolean
                default: false
              triggers:
                description: Триггеры вопроса
                type: array
                items:
                  $ref: '#/components/schemas/questionnaireTrigger'
            
      example:
        groups:
        - name: Общие сведения
          fields:
          - 8745cfbd-7913-11e8-95f0-000c29626b10
          - 6f79bdbc-7913-11e8-95f0-000c29626b10
        - name: Кабинет
          fields:
          - 64d0fa00-73b4-11e8-95f0-000c29626b10
          - b43e954d-73b4-11e8-95f0-000c29626b10
        - name: Персональный компьютер
          fields:
          - a55f7907-73b5-11e8-95f0-000c29626b10
          - be2b4e54-73b5-11e8-95f0-000c29626b10
          - f428e0e0-73b5-11e8-95f0-000c29626b10
          - 135ff13d-73b6-11e8-95f0-000c29626b10
        fields:
        - id: 8745cfbd-7913-11e8-95f0-000c29626b10
          name: Тема
          meta:
            value: ''
            type: String
          value: 
          visible: true
          available: true
          required: true
          triggers:
          - filter: 
            actions: []
        - id: 6f79bdbc-7913-11e8-95f0-000c29626b10
          name: Описание заявки
          meta:
            value: ''
            type: String
          value: 
          visible: true
          available: true
          required: true
          triggers:
          - filter: 
            actions: []
        - id: 64d0fa00-73b4-11e8-95f0-000c29626b10
          name: Адрес офиса
          meta:
            type: Enumeration
            args:
              values:
              - id: Тимме 2к1, офис 606
                title: Тимме 2к1, офис 606
              - id: Троицкий 95к1, офис 705
                title: Троицкий 95к1, офис 705
              - id: Галушино 22, офис 208
                title: Галушино 22, офис 208
          value: 
          visible: true
          available: true
          required: true
          triggers:
          - filter:
              operator: and
              nodes:
              - operator: equal
                value: Троицкий 95к1, офис 705
            actions:
            - type: state
              question: b43e954d-73b4-11e8-95f0-000c29626b10
              args:
                required: true
        - id: b43e954d-73b4-11e8-95f0-000c29626b10
          name: Руководитель
          meta:
            value: 00000000-0000-0000-0000-000000000000
            type: Reference
            args:
              reference: Справочник.ITEXP_Сотрудники
          value: 
          visible: true
          available: true
          required: false
          triggers:
          - filter: 
            actions: []
        - id: a55f7907-73b5-11e8-95f0-000c29626b10
          name: Тип персонального компьютера
          meta:
            type: Enumeration
            args:
              values:
              - id: Учебный
                title: Учебный
              - id: Офисный
                title: Офисный
              - id: Рабочая станция
                title: Рабочая станция
              - id: ''
                title: ''
          value: 
          visible: true
          available: true
          required: false
          triggers:
          - filter:
              operator: and
              nodes:
              - operator: equal
                value: Учебный
            actions:
            - type: state
              question: f428e0e0-73b5-11e8-95f0-000c29626b10
              args:
                visible: true
            - type: state
              question: 135ff13d-73b6-11e8-95f0-000c29626b10
              args:
                visible: true
          - filter:
              operator: and
              nodes:
              - operator: notEqual
                value: Учебный
            actions:
            - type: state
              question: 135ff13d-73b6-11e8-95f0-000c29626b10
              args:
                visible: false
            - type: state
              question: f428e0e0-73b5-11e8-95f0-000c29626b10
              args:
                visible: false
        - id: be2b4e54-73b5-11e8-95f0-000c29626b10
          name: Количество оперативной памяти
          meta:
            value: 0
            type: Float
          value: 
          visible: true
          available: true
          required: false
          triggers:
          - filter: 
            actions: []
        - id: f428e0e0-73b5-11e8-95f0-000c29626b10
          name: Наличие офисных программ
          meta:
            value: false
            type: Boolean
          value: 
          visible: false
          available: true
          required: false
          triggers:
          - filter: 
            actions: []
        - id: 135ff13d-73b6-11e8-95f0-000c29626b10
          name: Наличие графических программ
          meta:
            value: false
            type: Boolean
          value: 
          visible: false
          available: true
          required: false
          triggers:
          - filter: 
            actions: []