openapi: "3.0.0"
info:
  version: 2.0.0
  title: Petstore
  description: A sample API that uses a petstore as an example to demonstrate features in the OpenAPI 3.0 specification

paths:
  /pets:
    get:
      operationId: findPets
      responses:
        '200':
          description: pet response
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Pet'      
components:
  schemas:
    Pet:
      allOf:
        - $ref: '#/components/schemas/NewPet'
        - required:
          - id
          properties:
            id:
              type: integer
              format: int64

    NewPet:
      required:
        - name  
      properties:
        name:
          type: string
        tag:
          type: string