openapi: 3.0.0
info:
  version: 0.0.1
  title: ExternalReference
paths:
  /test:
    post:
      responses:
        '200':
          description: Опросник
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/foo'


components:
  schemas:
    foo:
      type: object
      properties:
        bar:
          $ref: 'schema.json#/definitions/filter'