openapi: 3.0.0
info:
  version: 0.0.1
  title: BusinessLogic
paths:
  /getAvailableEntitiesLocalization:
    post:
      summary: Возвращает локализованные имена сущностей
      tags:
        - Localization
      
      parameters:
        - name: culture
          in: query
          description: Код локали, в которой требуется вывести данные, в формате `<код языка>-<код культуры>`.
          required: true
          schema:
            type: string
          example: en-US

      responses:
        '200':
          description: Локализованные имена сущностей в виде объекта
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/getAvailableEntitiesLocalizationResponse'

components:
  schemas:
    getAvailableEntitiesLocalizationResponse:
      type: object
      description: Словарь `<Идентификтор>:<Имя>`
      additionalProperties:
        description: Локализованное имя сущности
        type: string
      example:
        Документ.ITEXP_Инцидент: Incident
        Документ.ITEXP_ЗНО: Service Request
