openapi: 3.0.0
info:
  version: 0.0.1
  title: BusinessLogic
paths:
  /getEntityMetadataLocalization:
    post:
      summary: Возвращает локализованные имена свойств сущностей
      tags:
        - Localization
      
      parameters:
        - name: culture
          in: query
          description: Код локали, в которой требуется вывести данные, в формате `<код языка>-<код культуры>`.
          required: true
          schema:
            type: string
          example: en-US
        - name: entity
          in: query
          description: Имя сущности, метаданные которой необходимо получить.
          required: true
          schema:
            type: string
          example: Документ.ITEXP_Инцидент

      responses:
        '200':
          description: Локализованные имена свойств
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/getEntityMetadataLocalizationResponse'
components:
  schemas:
    getEntityMetadataLocalizationResponse:
      type: object
      required: [entity, properties]
      properties:
        entity:
          description: Локализованное экранное имя сущности
          type: string
        properties:
          description: "Маппинг `{ <Свойство сущности>: <Локализованное имя свойства> }`"
          type: object
          additionalProperties:
            type: string
      example:
        entity: ITEXP_Инцидент
        properties:
          SLA: SLA
          ВнешнийID: Внешний ID
          ВремяРаботыНадОбращением: Время Работы Над Обращением
          ДатаВосстановления: Дата Восстановления