openapi: 3.0.0
info:
  version: 0.1.0
  title: FileService
  description: File management service.
  contact:
    name: n.batrakov
    email: n.batrakov@itexpert.ru

servers:
  - url: /api/fileservice

paths:
  /attachments/getFileLink:
    post:
      tags:
        - Download
      summary: Returns URL to a file chosen from Source by Parameters.
      description: Manages files attached to business object in 1C.
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetFileLinkResponse'
      requestBody:
        content:
          application/json:
            schema:
              required:
                - entity
                - attachmentId
              type: object
              properties:
                entity:
                  description: Entity to which file is attached.
                  type: string
                attachmentId:
                  description: Attachment ID.
                  type: string
        required: true


  /attachments/upload:
    post:
      tags:
        - Upload
      summary: >-
        Uploads file to chosen file Source with specified Parameters. Exactly
        one file must be specified in form data (any key).
      description: Manages files attached to business object in 1C.
      responses:
        '204':
          description: Success
      requestBody:
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                file:
                  description: The file to upload.
                  type: string
                  format: binary
                entity:
                  description: Entity to which file should be attached.
                  type: string
                ownerId:
                  description: ID of object to whic file should be attached.
                  type: string
              required:
                - file
                - entity
                - ownerId

components:
  schemas:
    GetFileLinkResponse:
      type: object
      properties:
        link:
          description: URL to a file relative to the service host.
          type: string
          readOnly: true
        filename:
          description: File name.
          type: string
          readOnly: true
    Data:
      type: object
      properties:
        id:
          format: uuid
          type: string
        number:
          format: int32
          type: integer
        someFlag:
          type: boolean