openapi: 3.0.0
info:
  version: 0.0.1
  title: BusinessLogic
paths:
  /executeObjectTransform:
    post:
      summary: Выполняет изменение экземпляра сущности по одной из существующих процедур
      description: |-
        Выполняет изменение экземпляра сущности по одной из существующих процедур.

        Возвращает изменения значений и метаданных полей (видимость, доступность, обязательность). В ответе присутствуют только измененные поля.

      tags:
        - Forms
      
      requestBody:
        description: No description
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/executeObjectTransformRequest'

      responses:
        '200':
          description: Обновление состояния объекта (патч)
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/executeObjectTransformResponse'
components:
  schemas:
    executeObjectTransformRequest:
      type: object
      required: [entity,procedureName, parameters]
      properties:
        entity:
          description: Имя сущности
          type: string
        procedureName:
          description: Идентификатор вызываемой процедуры
          type: string
        parameters:
          description: Полный экземпляр сущности
          type: object
          required: [entities]
          properties:
            entities:
              description: Экземпляр сущности
              type: array
              minItems: 1
              maxItems: 1
              items:
                description: "Маппинг `{ <Имя свойства>: <Значение свойства> }`"
                type: object
                additionalProperties:
                  description: "Значение свойства (напр., `{'value': false}`)"
                  type: object
                  required: [value]
                  properties:
                    value:
                      anyOf:
                        - type: string
                        - type: number
                        - type: boolean
                    referenceName:
                      description: Экранное имя ссылки
                      type: string
      example:
        entity: Документ.ITEXP_Инцидент
        procedureName: ПриИзмененииПользователя
        parameters:
          entities:
          - Номер:
              value: '123'
            Дата:
              value: '2018-07-05T13:18:17Z'
            Пользователь:
              referenceName: Администратор
              value: 4a46937f-e879-11e6-98ee-5404a638632e
            Инициатор:
              referenceName: Администратор
              value: 4a46937f-e879-11e6-98ee-5404a638632e
            Тема:
              value: Укажите тематику обращения
            Приоритет:
              referenceName: Плановый
              value: 0276ed2f-8dd2-11e7-9d32-000c29626b10
            Статус:
              referenceName: Зарегистрирован
              value: 0276ed3b-8dd2-11e7-9d32-000c29626b10
            ДатаОбнаружения:
              value: '2018-07-05T13:18:17Z'
          
    executeObjectTransformResponse:
      type: object
      required: [properties]
      properties:
        properties:
          type: object
          description: "Маппинг `{ <Имя свойства>: <значение свойства> }`"
          additionalProperties:
            type: object
            required:
              - value
              - visible
              - enable
              - required
            properties:
              value:
                description: Новое значение свойства
                anyOf:
                  - type: string
                  - type: number
                  - type: boolean
              referenceName:
                description: Экранное имя значение для ссылок
                type: string
              visible:
                description: Видимость
                type: boolean
              enable:
                description: Доступность
                type: boolean
              required:
                description: Обязательность
                type: boolean
      example:
        properties:
          Приоритет:
            value: 00000000-0000-0000-0000-000000000000
            referenceName: ''
            visible: true
            enable: true
            required: false
          СтруктурноеПодразделениеПользователя:
            value: 848c04e8-9a29-11e7-8de5-000c29626b10
            referenceName: Департамент ИТ услуг
            visible: true
            enable: true
            required: false
