openapi: 3.0.0
info:
  version: 0.0.1
  title: BusinessLogic
paths:
  /getBusinessProcessSchema:
    post:
      summary: Возвращает изображение схемы бизнес-процесса, ассоциированного с указанным объектом
      tags:
        - Forms

      parameters:
        - in: query
          name: entity
          description: Имя сущности
          required: true
          schema:
            type: string
          example: Документ.ITEXP_ЗапросНаОбслуживание
        - in: query
          name: objectId
          description: Идентификатор объекта сущности
          required: true
          schema:
            type: string
            format: guid
          example: "f2f3989d-793d-11e8-95f0-000c29626b10"

      responses:
        '200':
          description: Изображение схемы Бизнес-Процесса
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/getBusinessProcessSchemaResponse'

components:
  schemas:
    getBusinessProcessSchemaResponse:
      type: object
      required: [value]
      properties:
        value:
          description: Base-64 изображения
          type: string
          format: base64