openapi: 3.0.0
info:
  version: 0.0.1
  title: BusinessLogic
paths:
  /getHistoryObject:
    post:
      summary: Возвращает историю изменений объекта
      tags:
        - Forms

      parameters:
        - in: query
          name: entity
          description: Имя сущности
          required: true
          schema:
            type: string
          example: Документ.ITEXP_Инцидент
        - in: query
          name: objectId
          description: Идентификатор объекта сущности.
          required: true
          schema:
            type: string
            format: guid
          example: "8483eda8-72d1-11e8-95f0-000c29626b10"

      responses:
        '200':
          description: "Список проделанных действий над объектом"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/getHistoryObjectResponse'

components:
  schemas:
    getHistoryObjectResponse:
      type: object
      description: Список изменений
      required:
        - entities
      properties:
        entities:
          type: array
          items:
            description: "Маппинг { <Имя свойства>: <Значение свойства> }"
            type: object
            additionalProperties:
              description: Значение свойства
              type: object
              required: [value]
              properties:
                value:
                  anyOf:
                    - type: string
                    - type: number
                    - type: boolean
      example:
        entities:
          - "Ссылка":
              value: "..."