openapi: 3.0.0
info:
  version: 0.0.1
  title: BusinessLogic
paths:
  /getLifecycle:
    post:
      summary: Возвращает стадии жизненного цикла объекта на основе статуса или Бизнес-Процесса
      tags:
        - Forms

      parameters:
        - in: query
          name: entity
          description: Имя сущности
          required: true
          schema:
            type: string
          example: Документ.ITEXP_ЗапросНаОбслуживание
        - in: query
          name: objectId
          description: Идентификатор объекта сущности
          required: true
          schema:
            type: string
            format: guid
          example: "f2f3989d-793d-11e8-95f0-000c29626b10"

      responses:
        '200':
          description: Стадии жизненного цикла
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/getLifecycleResponse'

components:
  schemas:
    getLifecycleResponse:
      type: object
      required: [hasBusinessProcess, stages]
      properties:
        hasBusinessProcess:
          description: True, если с объектом связан активный бизнес-процесс
          type: boolean
        stages:
          description: Стадии жизненного цикла объекта
          type: array
          items:
            description: Стадаия жизненного цилка объекта
            type: object
            required: [name, isCompleted]
            properties:
              name:
                description: Локализованное экранное имя стадии
                type: string
              isCompleted:
                description: True, если стадия завершена
                type: boolean
      example:
        hasBusinessProcess: true
        stages:
        - name: На модерации
          isCompleted: true
        - name: Обработан
          isCompleted: true
        - name: В исполнении
          isCompleted: false
        - name: Исполнен
          isCompleted: false