openapi: 3.0.0
info:
  version: 0.0.1
  title: BusinessLogic
paths:
  /getUserRoles:
    post:
      summary: Возвращает роли текущего пользователя
      tags:
        - User
      responses:
        '200':
          description: Список ролей
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/getUserRolesResponse'

components:
  schemas:
    getUserRolesResponse:
      type: object
      required: [data]
      properties:
        data:
          type: array
          description: Список ролей
          items:
            description: Роль
            type: object
            required: [name]
            properties:
              name:
                description: Идентификатор роли
                type: string
      example:
        data:
          - name: ITEXP_Аналитик
          - name: ITEXP_Оператор
          - name: ITEXP_Специалист