openapi: 3.0.0
info:
  title: BusinessLogic
  version: 0.0.1
paths:
  /executeActions:
    post:
      tags:
      - Actions
      summary: Исполняет действия над указанными объектами одной сущности.
      description: |-
        Исполняет действия над указанными объектами одной сущности.

        Если указанно множество объектов, действие выполняется с одинаковыми для всех объектов параметрами. Действия при этом должны вызываться параллельно и не влиять друг на друга.
      requestBody:
        description: Описание вызываемого действия над объектами
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/executeActionsRequest'
        required: true
      
      responses:
        200:
          description: Список статусов выполнения действия над каждым из объектов
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/executeActionsResponse'
components:
  schemas:
    executeActionsRequest:
      type: object
      required:
        - entity
        - objects
        - action
        - parameters
      properties:
        entity:
          description: Имя сущности
          type: string
        objects:
          description: Id объектов, над которыми необходимо вызывать действия; строка
            с набором GUID разделенных запятой
          type: string
        action:
          description: Идентификатор действия
          type: string
        parameters:
          description: Параметры действия
          type: array
          items:
            type: object
            required: [name, type, value]
            properties:
              name:
                description: Идентификатор параметра
                type: string
              type:
                description: Тип данных параметры
                type: string
              value:
                description: Значение параметра
                type: string
      example:
        entity: Документ.ITEXP_Инцидент
        objects: df93fd03-bb23-11e7-91ca-000c29626b10,bec104b7-992b-11e7-8de5-000c29626b10
        action: ИзменитьПриоритет
        parameters:
        - name: Приоритет
          type: Справочник.ITEXP_ПриоритетыИнцидентов
          value: 0276ed2b-8dd2-11e7-9d32-000c29626b10
        - name: СтепеньВлияния
          type: Справочник.ITEXP_СтепениВлиянияИнцидентов
          value: 0276ed3c-8dd2-11e7-9d32-000c29626b10
    
    executeActionsResponse:
      type: array
      items:
        type: object
        required:
          - object
          - isFault
        properties:
          object:
            description: ID объекта над которым выполнилось действие
            type: string
          isFault:
            description: True, если действие выполнено успешно
            type: boolean
          message:
            description: Локализованное сообщение о статусе выполненного действия
            type: string
        example:
          - object: bec104b7-992b-11e7-8de5-000c29626b10
            isFault: false
          - object: df93fd03-bb23-11e7-91ca-000c29626b10
            isFault: true
            message: "..."