openapi: 3.0.0
info:
  version: 0.0.1
  title: BusinessLogic
paths:
  /archiveNews:
    post:
      summary: Отправляет новость в архив.
      tags:
        - News

      parameters:
        - in: query
          name: id
          description: Идентификатор новости
          required: true
          schema:
            type: string
            format: guid


      responses:
        '200':
          description: Статус операции
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/archiveNewsResponse'

components:
  schemas:
    archiveNewsResponse:
      type: object
      required: [success]
      properties:
        success:
          description: True, если действие выполнено успешно
          type: boolean
        message:
          description: Локализованное сообщение о статусе выполнения
          type: string