openapi: 3.0.0
info:
  version: 0.0.1
  title: BusinessLogic
paths:
  /countNews:
    post:
      summary: Возвращает количество новостей текущего пользователя
      tags:
        - News

      responses:
        '200':
          description: Количество новостей
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/countNewsResponse'

components:
  schemas:
    countNewsResponse:
      type: object
      properties:
        value:
          type: integer
          example: 1
          
        