openapi: 3.0.0
info:
  version: 0.0.1
  title: BusinessLogic
paths:
  /getNews:
    post:
      summary: Возвращает список новостей текущего пользователя
      tags:
        - News

      parameters:
        - in: query
          name: limit
          description: Количество возвращаемых новостей
          schema:
            type: integer
          example: 10
        - in: query
          name: offset
          description: Номер первой возвращаемой новости
          schema:
            type: integer
          example: 0

      responses:
        '200':
          description: Список новостей
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/getNewsResponse'

components:
  schemas:
    getNewsResponse:
      type: array
      items:
        type: object
        required: [id, title, content, isImportant]
        properties:
          id:
            type: string
            format: guid
          title:
            type: string
          content:
            type: string
            example: '<p><strong>Beware</strong>: News support basic HTML for formatting.</p>'
          isImportant:
            type: boolean
          activeFrom:
            type: string
            format: date
          activeTo:
            type: string
            format: date
          
        